In [23]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

Cargando la Data Original completa y verificando la estructura

In [24]:
df = pd.read_csv('esets_lung_exprs_genes.txt', sep="\t",header=None,index_col=0)
df.head()

,1,2,3,4,5,6,7,8,9,10,...,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621
0,,,,,,,,,,,,,,,,,,,,,
NaN,GSM258551.CEL,GSM258552.CEL,GSM258553.CEL,GSM258554.CEL,GSM258555.CEL,GSM258556.CEL,GSM258557.CEL,GSM258558.CEL,GSM258559.CEL,GSM258560.CEL,...,GSM748357.CEL,GSM748358.CEL,GSM748359.CEL,GSM748360.CEL,GSM748361.CEL,GSM748362.CEL,GSM748363.CEL,GSM748364.CEL,GSM748365.CEL,GSM748366.CEL
RFC2,7.42758244555227,7.52013606768351,8.60710702202386,7.55095069833604,8.74849398266653,8.52492137484236,7.75767286102677,7.05658915880431,8.12425062303228,8.73333916489109,...,7.60433976585752,8.07803400451642,8.74309051035448,8.29952281309729,8.63256057297409,8.42955733507609,8.73525760360266,7.72162848178536,8.71609010056984,7.73667164011289
HSPA6,6.54816125773337,7.64051736636398,7.53841574274325,6.62446731224566,7.32491892467417,8.78833806659679,9.95119825208557,6.77349324177506,9.15962974417968,7.58380826309187,...,7.95068103585715,8.33399487832174,8.51227113380798,7.44179981737415,7.12537406417474,8.46054129185827,8.2107320523269,8.33364850458931,7.96874384556658,7.79417278128641
PAX8,7.51113190990481,7.11449059793354,7.63188322595173,8.09771318026249,7.66345530229684,7.29163163451372,8.00936241743949,7.95618493168926,7.63811312097626,7.56816029806859,...,8.09228666611648,7.55773108785228,7.4193190706788,7.50852671227374,7.5037612717468,7.49447192064221,7.36197163404678,7.47849491019497,7.17620357757812,7.97055412279494
GUCA1A,5.89798759545012,5.36228352661111,6.01510325146066,5.77776199447971,5.58221445049765,5.42058462521047,5.33082778274708,5.81671683361456,5.45715010488022,5.54543888571819,...,5.74944841812353,5.25106098241579,6.23499403642666,6.28094574332716,5.3937428937626,5.34624643149829,5.55400704251223,5.82956737400681,5.64931446624338,5.82244507243215

In [25]:
df.shape

(20546, 1621)

Transponiendo- Genes como caracterÃ­sticas, Muestras a Filas

In [26]:
df2=df.transpose()
df2.head()

,nan,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
1,GSM258551.CEL,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
2,GSM258552.CEL,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
3,GSM258553.CEL,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
4,GSM258554.CEL,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
5,GSM258555.CEL,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

In [27]:
df2.columns=df2.columns.fillna('sample_name')
df2.head()

,sample_name,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
1,GSM258551.CEL,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
2,GSM258552.CEL,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
3,GSM258553.CEL,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
4,GSM258554.CEL,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
5,GSM258555.CEL,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

Uniformizando nombres de muestras

In [28]:
df2['sample_name']=df2['sample_name'].str[:9]
df2.head()

,sample_name,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
1,GSM258551,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
2,GSM258552,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
3,GSM258553,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
4,GSM258554,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
5,GSM258555,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

Creando el objetivo (CÃ¡ncer=1,No CÃ¡ncer=-1), extrayendo la data de resultados

In [29]:
df3=pd.read_csv('E-MTAB-6699.sdrf.txt', sep="\t",header=0,index_col=False)
df3.head()

,Source Name,Characteristics[organism],Characteristics[disease],Characteristics[GEO accession number],Material Type,Protocol REF,Protocol REF.1,Extract Name,Protocol REF.2,Labeled Extract Name,...,Protocol REF.3,Assay Name,Technology Type,Array Design REF,Term Source REF,Protocol REF.4,Protocol REF.5,Derived Array Data File,Comment [Derived ArrayExpress FTP file],Factor Value[disease]
0,GSM1019138,Homo sapiens,tumor,GSE37745,organism part,P-MTAB-74105,P-MTAB-74106,GSM1019138,P-MTAB-74107,GSM1019138:biotin,...,P-MTAB-74108,GSM1019138:biotin,array assay,A-AFFY-44,ArrayExpress,P-MTAB-74109,P-MTAB-74110,esets_lung_exprs_genes.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,tumor
1,GSM1019139,Homo sapiens,tumor,GSE37745,organism part,P-MTAB-74105,P-MTAB-74106,GSM1019139,P-MTAB-74107,GSM1019139:biotin,...,P-MTAB-74108,GSM1019139:biotin,array assay,A-AFFY-44,ArrayExpress,P-MTAB-74109,P-MTAB-74110,esets_lung_exprs_genes.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,tumor
2,GSM1019140,Homo sapiens,tumor,GSE37745,organism part,P-MTAB-74105,P-MTAB-74106,GSM1019140,P-MTAB-74107,GSM1019140:biotin,...,P-MTAB-74108,GSM1019140:biotin,array assay,A-AFFY-44,ArrayExpress,P-MTAB-74109,P-MTAB-74110,esets_lung_exprs_genes.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,tumor
3,GSM1019141,Homo sapiens,tumor,GSE37745,organism part,P-MTAB-74105,P-MTAB-74106,GSM1019141,P-MTAB-74107,GSM1019141:biotin,...,P-MTAB-74108,GSM1019141:biotin,array assay,A-AFFY-44,ArrayExpress,P-MTAB-74109,P-MTAB-74110,esets_lung_exprs_genes.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,tumor
4,GSM1019142,Homo sapiens,tumor,GSE37745,organism part,P-MTAB-74105,P-MTAB-74106,GSM1019142,P-MTAB-74107,GSM1019142:biotin,...,P-MTAB-74108,GSM1019142:biotin,array assay,A-AFFY-44,ArrayExpress,P-MTAB-74109,P-MTAB-74110,esets_lung_exprs_genes.txt,ftp://ftp.ebi.ac.uk/pub/databases/microarray/d...,tumor

In [30]:
list(df3.columns)

['Source Name',
 'Characteristics[organism]',
 'Characteristics[disease]',
 'Characteristics[GEO accession number]',
 'Material Type',
 'Protocol REF',
 'Protocol REF.1',
 'Extract Name',
 'Protocol REF.2',
 'Labeled Extract Name',
 'Label',
 'Protocol REF.3',
 'Assay Name',
 'Technology Type',
 'Array Design REF',
 'Term Source REF',
 'Protocol REF.4',
 'Protocol REF.5',
 'Derived Array Data File',
 'Comment [Derived ArrayExpress FTP file]',
 'Factor Value[disease]']

Extrayendo nombre de muestra='Extract Name' y Factor de Valor (tumor si o no)

In [31]:
df4=df3.drop(['Extract Name','Factor Value[disease]'],axis=1)
df5=df3.drop(df4,axis=1)

Convirtiendo el valor de Tumor a 0, 1

In [32]:
df5['Tumor']=np.where(df5['Factor Value[disease]']=='tumor',1 ,0)
df6=df5.drop(['Factor Value[disease]'],axis=1)
df6.head()

  Extract Name  Tumor
0   GSM1019138      1
1   GSM1019139      1
2   GSM1019140      1
3   GSM1019141      1
4   GSM1019142      1

In [33]:
df6.shape

(1621, 2)

Recuperando df2

In [34]:
df2.head()

,sample_name,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
1,GSM258551,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
2,GSM258552,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
3,GSM258553,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
4,GSM258554,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
5,GSM258555,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

Verificando si hay valores nulos

In [45]:
null_columns4=df2.columns[df2.isna().any()]

df2[null_columns4].isna().sum()

Series([], dtype: float64)

Combinando las celdas para obtener los valores resultado

In [50]:
df7=df2.merge(df6,how='left',left_on='sample_name',right_on='Extract Name',left_index=True)

In [51]:
df2.shape

(1621, 20546)

In [52]:
df7.head()

,sample_name,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915,Extract Name,Tumor
429,GSM258551,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624,GSM258551,1.0
430,GSM258552,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364,GSM258552,1.0
431,GSM258553,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131,GSM258553,1.0
432,GSM258554,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355,GSM258554,1.0
433,GSM258555,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667,GSM258555,1.0

In [53]:
df7.shape

(1621, 20548)

In [54]:
df7.iloc[0:10,20546:20548]

    Extract Name  Tumor
429    GSM258551    1.0
430    GSM258552    1.0
431    GSM258553    1.0
432    GSM258554    1.0
433    GSM258555    1.0
434    GSM258556    1.0
435    GSM258557    1.0
436    GSM258558    1.0
437    GSM258559    1.0
438    GSM258560    1.0

In [55]:
df7=df7.drop(['Extract Name'],axis=1)
df7.shape

(1621, 20547)

In [56]:
df7.iloc[0:10:,20545:20547]

    LOC100505915  Tumor
429      5.93624    1.0
430      5.66364    1.0
431      5.15131    1.0
432      5.01355    1.0
433      5.34667    1.0
434      5.64369    1.0
435      5.47553    1.0
436      5.68092    1.0
437      4.95782    1.0
438      5.28147    1.0

In [57]:
print(df7['Tumor'].nunique())

2

Se asegurÃ³ la coincidencia de grupos de datos (Muestras y resultados). Ahora se separan nuevamente para proceder a la ReducciÃ³n de dimensionalidad. Se anula la columna de muestras y se convierte en tÃ­tulo de filas para permitir usos numÃ©ricos.

In [58]:
df2.to_csv('CancerPulmon_ds.csv',header=True,index=True)

In [59]:
df_caract=df7.drop('Tumor',axis=1)
df_result=df7.drop(df_caract,axis=1)
df_caract.head()

,sample_name,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
429,GSM258551,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
430,GSM258552,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
431,GSM258553,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
432,GSM258554,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
433,GSM258555,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

In [60]:
df_result.head()

     Tumor
429    1.0
430    1.0
431    1.0
432    1.0
433    1.0

In [61]:
nombres=df_caract['sample_name']
df_caract.rename(mapper=nombres,axis=0,inplace=True)
df_caract=df_caract.drop(['sample_name'],axis=1)
df_caract.head()

,RFC2,HSPA6,PAX8,GUCA1A,THRA,PTPN21,CCL5,CYP2E1,EPHB3,ESRRA,...,NAF1,CCDC63,C16orf52,LOC101929475,LOC389641,LOC400499,GALR3,NUS1P3,TMEM231,LOC100505915
GSM258551,7.42758244555227,6.54816125773337,7.51113190990481,5.89798759545012,6.35277132078249,6.3165506567819,9.06605407530796,4.9840916184553,7.72358832790834,7.69131110652345,...,6.12457,4.45625,3.50302,4.17653,5.34322,6.78441,6.16056,4.18889,5.8979,5.93624
GSM258552,7.52013606768351,7.64051736636398,7.11449059793354,5.36228352661111,6.11920219091691,7.60694950208702,9.9221180181805,6.25912584647201,7.20798107903431,7.46683534518673,...,6.08287,4.61637,3.67727,4.40539,4.75759,6.40126,5.5515,4.50505,5.06598,5.66364
GSM258553,8.60710702202386,7.53841574274325,7.63188322595173,6.01510325146066,6.56746941647352,4.96884640647012,9.88687858564922,4.77365849577781,7.95841747036874,7.29318229157693,...,6.78802,5.00605,3.84554,4.4489,4.79452,6.04886,6.36346,4.62658,6.43551,5.15131
GSM258554,7.55095069833604,6.62446731224566,8.09771318026249,5.77776199447971,6.91186138232416,7.23791939561862,8.43337618911167,7.05750126660718,7.6001281227017,7.79220201325052,...,7.3737,4.9387,3.46274,4.28529,5.0895,6.51232,6.30356,4.52943,6.97467,5.01355
GSM258555,8.74849398266653,7.32491892467417,7.66345530229684,5.58221445049765,6.35217681445702,6.95537841900929,7.23790227016079,6.53676635735515,8.95116152465713,8.03119162926749,...,7.01699,4.45247,3.86656,4.22638,4.6499,5.79015,5.82199,4.29849,7.81869,5.34667

In [67]:
df_caract.shape

(1621, 20545)

Primer entregable: La data preparada para trabajarse con tres mÃ©todos distintos de reducciÃ³n. Se generan los dos archivos de conjunto de datos: - Datos de caracterÃ­sticas (GenCaracterist.csv) y Datos de resultados (CancerResul.csv)

In [68]:
df_caract.to_csv('GenCaracterist.csv',header=True,index=True)

In [69]:
df_result.to_csv('CancerResul.csv',header=True,index=True)

Separando la data de test, se realiza por una sola vez, Se prepara verificaciÃ³n si archivo ya existe

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df_caract,df_result,test_size=0.1,random_state=42)

In [66]:
print("TamaÃ±os de Conjuntos: \n X_train = ",X_train.shape,"\n X_test =", X_test.shape,"\n y_train =",y_train.shape,"\n y_test =",y_test.shape)

TamaÃ±os de Conjuntos:
 X_train =  (1458, 20545)
 X_test = (163, 20545)
 y_train = (1458, 1)
 y_test = (163, 1)

Cargando la data por una Ãºnica vez como archivos de trabajo, Si ya se habia descargado, imprime  Falso

In [72]:
import os.path

In [73]:
def Unica_Carga_Archivos(Nombre,dato):
    no_imprimir=os.path.isfile(Nombre)
    if not no_imprimir:
        dato.to_csv(Nombre,header=True,index=True)
    return(Nombre,not no_imprimir)

In [74]:
Arch1,impr1=Unica_Carga_Archivos('df_carac_train.csv',X_train)
Arch2,impr2=Unica_Carga_Archivos('df_carac_test.csv',X_test)
Arch3,impr3=Unica_Carga_Archivos('df_y_train.csv',y_train)
Arch4,impr4=Unica_Carga_Archivos('df_y_test.csv',y_test)

In [75]:
print ('Archivos descargados \n', Arch1," ",impr1,"\n",Arch2,' ',impr2,"\n",Arch3,' ',impr3,'\n',Arch4,' ',impr4)

Archivos descargados
 df_carac_train.csv   True
 df_carac_test.csv   True
 df_y_train.csv   True
 df_y_test.csv   True

EvaluaciÃ³n Inicial